Added sfdx authURL authentication
Accenture/sfpowerkit pull request #555
Opened 2021-08-16 06:36 UTC by henry88lay

Smoke tests have been repeatedly failing when pull requests are raised.  
![Screen Shot 2021-08-16 at 4 33 37 pm](https://user-images.githubusercontent.com/40649970/129521042-48ed5060-2604-4c86-a70b-bbef4afba9a2.png)

I looked into azure devOps to inspect the error and found this.
![Screen Shot 2021-08-16 at 4 33 54 pm](https://user-images.githubusercontent.com/40649970/129521179-74b04aa1-c8c0-4146-a0de-9e0e466e721e.png)

Updated the authentication to AuthURL

2021-08-16 06:46 UTC, azlam-abdulsalam requested changes
Please make the changes

2021-08-16 06:46 UTC, azlam-abdulsalam commented on templates/smoke-test-template.yml
> +  - task: sfppowerkit-authenticateorg-task@9
This should be a command line task

2021-08-16 07:02 UTC, henry88lay commented
authfile JSON has been uploaded to library.

2021-08-17 03:37 UTC, henry88lay commented
Tested Pipeline and here are screenshots
![Screen Shot 2021-08-17 at 1 32 37 pm](https://user-images.githubusercontent.com/40649970/129659745-d2f72d23-df50-42ae-9886-263ef7bd0631.png)

2021-08-17 04:06 UTC, merged